version: "3"

services:
  kanban:
    image: ghcr.io/plankanban/planka:latest
    container_name: kanban
    restart: on-failure
    ports:
      - "${PLANKA_PORT}:1337"
    environment:
      - BASE_URL=${BASE_URL}
      - TRUST_PROXY=${TRUST_PROXY}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      # Admin credentials
      - DEFAULT_ADMIN_EMAIL=${PLANKA_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${PLANKA_ADMIN_PASSWORD}
      - DEFAULT_ADMIN_NAME=${PLANKA_ADMIN_NAME}
      - DEFAULT_ADMIN_USERNAME=${PLANKA_ADMIN_USERNAME}
    depends_on:
      - postgres
    volumes:
      - kanban-files:/app/public/user-files
      - kanban-user-avatars:/app/public/user-avatars
      - kanban-project-background-images:/app/public/project-background-images
      - kanban-attachments:/app/private/attachments

  postgres:
    image: postgres:15-alpine
    container_name: kanban-postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - kanban-db:/var/lib/postgresql/data

volumes:
  kanban-db:
  kanban-files:
  kanban-user-avatars:
  kanban-project-background-images:
  kanban-attachments:
