version: "3"

services:
  planka:
    image: ghcr.io/plankanban/planka:latest
    container_name: planka
    restart: unless-stopped
    ports:
      - "${PLANKA_PORT}:3000"
    environment:
      - BASE_URL=${BASE_URL}
      - TRUST_PROXY=${TRUST_PROXY}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      # Admin credentials
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
    depends_on:
      - postgres
    volumes:
      - planka-files:/app/public/user-files

  postgres:
    image: postgres:15-alpine
    container_name: planka-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - planka-db:/var/lib/postgresql/data

  mcp-kanban:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-kanban
    restart: unless-stopped
    ports:
      - "${MCP_KANBAN_PORT}:3008"
    environment:
      - PLANKA_BASE_URL=${PLANKA_BASE_URL}
      - PLANKA_AGENT_EMAIL=${PLANKA_AGENT_EMAIL}
      - PLANKA_AGENT_PASSWORD=${PLANKA_AGENT_PASSWORD}
      - SERVER_PORT=${SERVER_PORT}
    depends_on:
      - planka

volumes:
  planka-db:
  planka-files:
